spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate: 
            ddl-auto: update
        show-sql: true
        generate-ddl: true
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: manager
        url: jdbc:postgresql://localhost:5432/meubanco
